# Generated by Django 3.1.7 on 2021-09-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Experience Short Description',
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percnt', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'My Experiences',
            },
        ),
        migrations.CreateModel(
            name='LeftMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@gmail.com', max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'My Messages',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'My Services',
            },
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percnt', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'My Skills',
            },
        ),
        migrations.CreateModel(
            name='SkillsDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Skills Short Description',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/teams/')),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'My Teams',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='TDBSoft', max_length=100)),
                ('business_address', models.CharField(default='1235 Street-Kisumu', max_length=100)),
                ('business_email', models.EmailField(default='infotdbsoft@gmail.com', max_length=255)),
                ('bio', models.TextField(default='my bio here')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='media/bg/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='media/cv/')),
                ('phone', models.CharField(default='+254743793901', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'About Me',
            },
        ),
    ]
