# Generated by Django 3.1.7 on 2021-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0006_auto_20210907_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(default='my bio here'),
        ),
    ]
