# Generated by Django 3.1.7 on 2021-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0008_auto_20210907_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
