# Generated by Django 3.1.7 on 2021-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0009_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='content',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='content',
        ),
    ]
