# Generated by Django 3.1.7 on 2021-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0010_auto_20210907_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@gmail.com', max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
