# Generated by Django 3.1.7 on 2021-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0011_leftmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/cv/'),
        ),
    ]
