# Generated by Django 3.1.7 on 2021-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0012_about_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='expdesc',
            options={'verbose_name_plural': 'Experience Short Description'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'My Experiences'},
        ),
        migrations.AlterModelOptions(
            name='leftmessage',
            options={'verbose_name_plural': 'My Messages'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'My Services'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'My Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillsdesc',
            options={'verbose_name_plural': 'Skills Short Description'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'My Teams'},
        ),
        migrations.AddField(
            model_name='about',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='+254711349412', max_length=15),
        ),
    ]
