# Generated by Django 3.1.7 on 2021-09-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0013_auto_20210912_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='business_name',
            field=models.CharField(blank=True, default='business name', max_length=100, null=True),
        ),
    ]
