# Generated by Django 3.1.7 on 2021-09-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0017_auto_20210912_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/bg/'),
        ),
    ]
