# Generated by Django 3.1.7 on 2021-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0018_about_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='business_address',
            field=models.CharField(default='1235 Street-Kisumu', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='business_email',
            field=models.EmailField(default='infotdbsoft@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='business_name',
            field=models.CharField(default='TDBSoft', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='+254743793901', max_length=15),
        ),
        migrations.AlterField(
            model_name='experience',
            name='percnt',
            field=models.IntegerField(default=2),
        ),
    ]
